### PR TITLE
Adding github deployment.

### PR DESCRIPTION
**Pull request by crspeller**

### CODE REVIEW

**Comment by lkraav** [comment]
Package available on Releases page wouldn't install this morning. Does this commit help?

**Comment by hanzei** [comment]
This PR makes sure future releases get automaticity build. I'm not aware of issues with the current `v1.0.0` release. Would you please open an issue of this?

**Comment by crspeller** [comment]
Ticket tracking the problem with `v1.0.0` https://mattermost.atlassian.net/browse/MM-16155

**Comment by lkraav** [comment]
Yep, that's exactly what I'm experiencing.

**Pull request merged**
