### PR TITLE
[MM-38146] Use mattermost-server/v6

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
This PR updates the dependency on `github.com/mattermost/mattermost-server` from `v5` to `v6`. This ensures the v6 breaking changes propagate quickly to developers using this plugin.

Please note that the plugin still works against v5 servers.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38146

### CODE REVIEW

**Comment by hanzei** [comment]
@streamer45 @mickmister This is ready for review

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Comment by hanzei** [comment]
@DHaussermann This PR is ready for a round of smoke testing. Maybe we can even defer that to the release testing.

**Comment by hanzei** [comment]
@DHaussermann I'm going to defer the QA approval to release testing.

**Pull request merged**
