### PR TITLE
Add test case for JIRA ticket to full URL

### PR DESCRIPTION
**Pull request by grubbins**
In my organisation, we use the plugin to go from either:
* `JIRA-1234`, or
* `https://jira/browse/JIRA-1234`
to a shortened `[JIRA-1234](https://jira/browse/JIRA-1234/stuff)` link. This did not work in earlier versions of the plugin so we have for a while been running my forked version - however, I believe this now works. I just wanted to reflect this in the unit tests.

### CODE REVIEW

**Comment by levb** [comment]
Needs https://github.com/mattermost/mattermost-plugin-autolink/pull/80 to fix the build, also @grubbins did you have a chance to sign the CLA? Or is our CLA bot mis-functioning?

**Comment by grubbins** [comment]
I am working on getting the CLA signed - need to clear this with my employer.

**Comment by hanzei** [comment]
Thanks for adding this test case @grubbins :+1:

**Pull request merged**
