### PR TITLE
Release v1.4.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Release for https://github.com/mattermost/mattermost-plugin-autolink/pull/201

#### Ticket Link
Part of #202

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by DHaussermann** [comment]
@mickmister or @hanzei I'm running through the release test now but, I wonder why there is no CI for `build`?

For release testing as a precaution, I like to use the binary that came from the pipeline instead of compiling locally. Does CI produce a build here I can use?

**Comment by mickmister** [comment]
@DHaussermann The branch needed an update to have the github action workflows. Check the bottom of this page for the built plugin https://github.com/mattermost/mattermost-plugin-autolink/actions/runs/4437991164?pr=203

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Reviewed code changes since last release
- Added one test to cover a functional change
- Ran through all tests in Zephyr
- No new issues found
- As a precaution ran the binary from the pipeline on both a Mac OS hosted Mattermost instance as well as our Cloud infrastructure
- Version bump is correct at `1.4.0`

LGTM!

**Pull request merged**
