### PR TITLE
Bump version to 1.2.0

### PR DESCRIPTION
**Pull request by jfrerich**
### Summary
Bump version to v1.1.3

Proposal to bump Minor Version to prep for release with the following Release Notes:

#### Enhancements 
* 5e53e3f Add AutoCompleteDesc (#92)
* d67f2d5 Add more manifest metadata (#86)
* 8c82b7d MM-17818 Adding API for adding/replacing links. (#85)
* dedc5ac Add option to enable processing on post update (#79)
* 4a25236 Migrate logging to use RPC Logging methods (#102)
* a10f0ee [GH-84] Add the concept of plugin admins (#93)

#### Fixes
* 542fab8 Add test case for JIRA ticket to full URL (#78)
* a646d82 [GH-84] Do not rewrite messages from bots (#98)

### Ticket Link
https://mattermost.atlassian.net/browse/MM-23175

#### Outstanding PRs

- [x] #98
- [x] #93

- [x] Update Enhancements/Fixes section above (after outstanding PRs added)

### CODE REVIEW

**Comment by hanzei** [comment]
Why is this a patch release if features are added?

**Comment by jfrerich** [comment]
@hanzei you are correct. I'll keep the branch and increment the feature, not the patch

**Comment by jfrerich** [comment]
The following PRs are outstanding. They aren't labeled for this release but it would be great if we could get them in first.

**Comment by hanzei** [comment]
All PR for this release have been merged :rocket:

**Comment by jfrerich** [comment]
Thanks for the update on #98, @hanzei! 

@aaronrothschild, @DHaussermann we can tag autolink with release version `v1.2.0` once PM and QA reviews are complete.

**Comment by DHaussermann** [comment]
@jfrerich 1 thing failed during End to End testing. 
Autolink is re-writing bot posts. Seems like it's simply a matter of syncing the version bump branch from master so it includes this PR https://github.com/mattermost/mattermost-plugin-autolink/pull/98
Let me know if you can merge in.

**Comment by levb** [comment]
@DHaussermann since we don't branch for the release - you can just test `master` perhaps?

I can merge the master changes into this PR, but the release will be cut from master anyway.

**Pull request merged**
