### PR TITLE
Fix crash on DMs

### PR DESCRIPTION
**Pull request by ThiefMaster**
This should ideally have tests (I don't have time for that atm) and it might be better to check the message type instead, but I needed a quick fix anyway so here's a PR with my fix.

### CODE REVIEW

**Comment by hanzei** [comment]
Just to double check: This is a regression from v0.4.0, correct?

**Comment by ThiefMaster** [comment]
yes, the bug got introduced in #43

**Comment by jespino** [comment]
I'll try to publish a 0.5.1 release later today

**Comment by jespino** [comment]
@ThiefMaster @hanzei Published the 0.5.1 version, thanks a lot!

**Pull request merged**
